### ISSUE TITLE
Extract info

### ISSUE THREAD

**Issue by andfy** [chan0park/video-annotation-tool#1]
Hi,

This tool seems to be very promising.
Would you make available in this repo the `extract_frame_info.py` file as highlighted in the readme?

Thank you.

**Comment by chan0park** [comment]
Hi,  Thank you for letting me know this issue. I just added the `extract_frame_info.py` file.

**Comment by andfy** [comment]
`image_diff.py` and `image_to_text.py` are imported in `extract_frame_info.py` but missing in the repo.
